### ISSUE TITLE
Puerto Rico as a US State

### ISSUE THREAD

**Issue by Nickigreen** [krokedil/klarna-payments-for-woocommerce#79] opened 2018-06-27 05:03 UTC
Is there a way that I can get Puerto Rico to display as a state in the drop-down list of US states? Thanks

**Comment by MichaelBengtsson** [comment] 2018-06-27 07:30
@Nickigreen This is a duplicate of #65. I will close this issue and we can continue this discussion there.

**Closed by MichaelBengtsson** 2018-06-27 07:30 UTC
