### ISSUE TITLE
Enhancement - support Woo Pay Link functionality (so KP can be included in draft order payment options)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#128] opened 2019-04-23 18:37 UTC
Hopefully this could share code with related KCO ticket: https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/182

Until this functionality is supported, Klarna merchants could use the Seller's App in the Klarna Merchant Portal, for more info, see: https://docs.krokedil.com/article/149-klarna-order-management#h-H2_7

**Comment by martinowren** [comment] 2021-02-03 21:15
Do we have any updates on this?

**Comment by martinowren** [comment] 2021-02-03 21:16
From the answer from @MichaelBengtsson, it looks like the cart is required for the checkout. But I don't know what info you cannot fetch from a WC order that you can with a cart?

**Comment by kristibarbosky** [comment] 2021-02-03 21:17
Hi @martinowren  - this ticket is prioritized to be developed soon, so hopefully there will be a good update coming.

**Comment by martinowren** [comment] 2021-02-03 21:26
@kristibarbosky I can contribute if it is needed, but I would need a quick walkthrough of the plugin as well as a little overview of the changes that need to be made.

**Comment by MichaelBengtsson** [comment] 2021-02-04 13:14
@martinowren I have been working on this today and i have a first working version already. I just need to go over the code, and test things before i can push it to a test version. After that if you are willing to test it out before a release that would be welcome. The coding part for KP is quite complicated since a lot of the logic happens in the JavaScript between us and Klarna, so I'm not sure how much you would be able to help without some decent knowledge about Klarnas systems sadly. But the code is mostly done already, and just tweaking and error handling is left to do.

**Comment by martinowren** [comment] 2021-02-04 13:32
Hi Michael!
I would love to help out! Just hit me up here with a built plugin (zip preferably) and I will test it out!

**Comment by MichaelBengtsson** [comment] 2021-02-05 16:34
Hi @martinowren 

The plan right now is to do internal testing next week. And then after that we would feel comfortable sending it out to merchants to test or make a release. The reason we want to do internal testing first is that we had to do some changes in logic that effects the normal checkout flow as well. So to make sure we dont break something else, we would want to run through our QA first.

So i would say that ETA for a test version would be towards the end of next week.

**Comment by MichaelBengtsson** [comment] 2021-02-11 14:07
@martinowren We now have a release candidate for the new feature if you want to use it on your two customers. You can find the release here: https://github.com/krokedil/klarna-payments-for-woocommerce/releases/tag/2.3.0-rc.1

I do however recommend that you keep an eye on it and check that everything is working as intended. If everything looks good it will be included in the next full release.

**Comment by martinowren** [comment] 2021-02-11 14:24
Hi! Installed and checked. Everything works as of now, will have clients check it today!

**Comment by martinowren** [comment] 2021-02-12 09:10
Hi @michaelbengtsson !

One client managed to use it without problems, so I think it is good to go!

Thanks again!

**Comment by MichaelBengtsson** [comment] 2021-02-12 10:21
@martinowren Thank you! We will do some more testing on our end before making a new release just to check for everything. The release should be coming out next week or the one after that.

**Comment by martinowren** [comment] 2021-02-16 20:26
Hi @MichaelBengtsson !

I think I found a bug. Right now listeners of type `change` cannot be used on the klarna checkout and only klarna that is.

**Comment by MichaelBengtsson** [comment] 2021-02-16 20:33
Hi again @martinowren Can you explain the issue a bit more? Im not quite sure i know what you mean with "listeners of type change".

**Comment by martinowren** [comment] 2021-02-16 20:42
Hi @MichaelBengtsson !

I have a JavaScript listener that listens on the 'change' event of all `input[name="payment_method"]`. This should do a console.log of a string when changed. But it seems like only other payment gateways work, not klarna ones.

**Comment by martinowren** [comment] 2021-02-16 20:48
Aswell, I am having issues attaching fee's to the cart when klarna is activated. 

`WC()->session->get('chosen_payment_method')` is never klarna_payments_pay_later or klarna_payments_pay_over_time

**Comment by MichaelBengtsson** [comment] 2021-02-16 20:50
Are you getting this on the pay for order links? Or when you go to the cart?

I think the issue here might be that when you pay for an already existing order, there are no input fields nor are there any sessions at all. That you get it working on other payment methods for pay for order links is strange however.

**Comment by martinowren** [comment] 2021-02-16 20:51
Right now this is only for the cart, not pay for order links.

**Comment by MichaelBengtsson** [comment] 2021-02-16 20:53
Do you see any JavaScript errors at all? We dont touch the fields from what i know, so we should not be effecting this

**Comment by martinowren** [comment] 2021-02-16 20:55
No errors. I think the frontend JS is something with the theme, which I will investigate further. But do you have any idea why `WC()->session->get('chosen_payment_method')` never is klarna_payments_pay_later or klarna_payments_pay_over_time in the cart?

**Comment by MichaelBengtsson** [comment] 2021-02-16 21:58
It could be due to the same thing if changes to the inputs are not triggered. Also on the top of my head, im not sure if you will ever be able to see if its pay later or pay over time for example, i think we change them all to klarna_payments to be able to support things that effect payment gateways better. Like currency switchers and gateway specific fees and discounts. Since we have no idea what the payment methods will actually be, and they are different in different regions we cant really get around that issue. Which means that we will have to change them to just be considered "klarna_payments".

**Comment by martinowren** [comment] 2021-02-16 22:01
Switching the conditional to check for "klarna_payments" corrected the issue. Also confirmed that the JS issue is a theme bug. Thanks for the help!

**Comment by MichaelBengtsson** [comment] 2021-02-17 08:29
Perfect! Glad i could help! And thank you for confirming the JS issue.

**Comment by MichaelBengtsson** [comment] 2021-03-02 14:51
Closing this issue since this has now been fully released!

**Closed by MichaelBengtsson** 2021-03-02 14:51 UTC
Labels: enhancement, has fix
